# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:14.7
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
