# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:14.7
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # Set the name of the database
    ports:
      - 5432:5432
