# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Go

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  # Label of the container job
  test:
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          envkey_PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
          envkey_DB_URL: ${{ secrets.DB_URL }}
          file_name: .env
          fail_on_empty: true
          sort_keys: false

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yaml up

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Test
        run: make test
